name: encrypt_file_loader
description: encrypt_file_loader is a library that can store files encrypted with webcrypto.
version: 4.1.0
homepage: https://github.com/koji-1009/encrypt_file_loader

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1

  # db
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.0

  path_provider: ^2.0.0
  path: ^1.8.0

  # decrypt
  webcrypto: ^0.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.0.0
  drift_dev: ^2.16.0

flutter:
